services:
  backend:
    build:
      context: ./backend/AlbertaAqi.Api
      dockerfile: Dockerfile
    ports:
      - "5223:8080"
    environment:
      POSTGRES_CONNECTION: "Host=alberta-aqi-db.cby6k8q0mhnk.ca-central-1.rds.amazonaws.com;Port=5432;Database=alberta_aqi;Username=aqi_user;Password=${RDS_PASSWORD};SSL Mode=Require;Trust Server Certificate=true"
      OPENAQ_API_KEY: ${OPENAQ_API_KEY}
      ASPNETCORE_ENVIRONMENT: Production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend